repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: trailing-whitespace
      exclude: ^myenv/
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: ^myenv/
